@url_dev = http://localhost:8080/v1/api


### singup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 3f0026b44fa0cd6ae0f797334d67b89c13e5db585d666c1fa454e80bbe3c10b3

{
    "name": "test3",
    "email": "test3@gmail.com",
    "password": "123456"
}