@url_dev = http://localhost:8080/v1/api


### singup

POST {{url_dev}}/shop/signup
Content-Type: application/json
# apikey

{
    "name": "test3",
    "email": "test3@gmail.com",
    "password": "123456"
}